### ISSUE TITLE
服务重启Ticker计数重置重新计算after时间分割不就乱了？

### ISSUE THREAD

**Issue by un-human** [Me1onRind/logrotate#1]

**Comment by Me1onRind** [comment]
不是很理解这个问题,   每一次After的时间都是内存中实时计算的，和服务是否重启无关。
如果你的进程被kill掉了，进程下所有的协程也会随着一起结束。

**Comment by un-human** [comment]
> 不是很理解这个问题, 每一次After的时间都是内存中实时计算的，和服务是否重启无关。 如果你的进程被kill掉了，进程下所有的协程也会随着一起结束。

0点发布服务，配置24小时按天分割日志， 12点中途更新服务(服务kill重发服务配置不变)，那通过Ticker 分割的日志还是第二天的0点按天分割吗？

**Comment by Me1onRind** [comment]
现在计算分割时间计算方法产生的行为应该是
按1分钟分割,  每分钟的0秒 分割
按1小时分割,  每小时的0分 分割

没有考虑到可以设置分割的"锚点"，如果是24小时, 现在应该是北京时间的8点切割。

```go
func CalRotateTimeDuration(now time.Time, duration time.Duration) time.Duration {
	nowUnixNao := now.UnixNano()
	NanoSecond := duration.Nanoseconds()
	nextRotateTime := NanoSecond - (nowUnixNao % NanoSecond)
	return time.Duration(nextRotateTime)
}
```

**Comment by un-human** [comment]
> 


按天分割啊，当天的.log  只保存当天的0点到23:59:59的日志，ticker在重启之后日志就无法按天记录了
